grapesjs.plugins.add('gjs-layout', function(editor, opts) {
  var bm = editor.BlockManager;

  bm.add('sidebar-layout', {
    label: 'Sidebar Layout', category: 'Layout', attributes: { class: 'fa fa-columns' },
    content: '<div class="cs-sbl"><div class="cs-sbl-main"><h2>Main Content Area</h2><p>This is the main content area. Place your primary content here. The sidebar on the right is great for navigation, widgets, ads or secondary information.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p></div><aside class="cs-sbl-side"><div class="cs-sbl-widget"><h4>About</h4><p>Short description or bio text goes here in the sidebar widget.</p></div><div class="cs-sbl-widget"><h4>Categories</h4><ul><li><a href="#">Design</a></li><li><a href="#">Development</a></li><li><a href="#">Marketing</a></li><li><a href="#">Business</a></li></ul></div><div class="cs-sbl-widget cs-sbl-cta"><h4>Newsletter</h4><p>Subscribe for weekly updates.</p><input type="email" placeholder="Your email" class="cs-sbl-input"><button type="button" class="cs-sbl-btn">Subscribe</button></div></aside></div><style>.cs-sbl{padding:40px 20px;font-family:Helvetica,sans-serif;max-width:1100px;margin:0 auto;}.cs-sbl{display:flex;gap:40px;align-items:flex-start;flex-wrap:wrap;}.cs-sbl-main{flex:1;min-width:260px;color:#444;line-height:1.7;}.cs-sbl-main h2{font-size:1.6em;font-weight:700;color:#333;margin-bottom:16px;}.cs-sbl-main p{margin-bottom:16px;font-size:.93em;}.cs-sbl-side{width:280px;flex-shrink:0;}.cs-sbl-widget{background:#fafafa;border-radius:8px;padding:20px;margin-bottom:20px;border:1px solid #eee;}.cs-sbl-widget h4{font-size:.95em;font-weight:700;color:#333;margin:0 0 12px;text-transform:uppercase;letter-spacing:1px;}.cs-sbl-widget p{font-size:.85em;color:#777;line-height:1.5;margin:0 0 10px;}.cs-sbl-widget ul{list-style:none;padding:0;margin:0;}.cs-sbl-widget ul li{padding:6px 0;border-bottom:1px solid #eee;font-size:.88em;}.cs-sbl-widget ul a{color:#4d114f;text-decoration:none;font-weight:500;}.cs-sbl-cta{background:#4d114f;border-color:#4d114f;}.cs-sbl-cta h4,.cs-sbl-cta p{color:#fff;opacity:.9;}.cs-sbl-input{width:100%;padding:9px 12px;border-radius:4px;border:none;font-size:.88em;margin-bottom:8px;box-sizing:border-box;}.cs-sbl-btn{width:100%;padding:9px;background:#a0449e;color:#fff;border:none;border-radius:4px;font-weight:700;cursor:pointer;font-size:.88em;}@media(max-width:700px){.cs-sbl-side{width:100%;}}</style>'
  });

  bm.add('spacer-divider', {
    label: 'Spacer / Divider', category: 'Layout', attributes: { class: 'fa fa-minus' },
    content: '<div class="cs-dividers"><div class="cs-div-item"><div class="cs-divider cs-div-line"></div></div><div class="cs-div-item"><div class="cs-divider cs-div-dots"><span></span><span></span><span></span></div></div><div class="cs-div-item"><div class="cs-divider cs-div-text"><span>OR</span></div></div><div class="cs-div-item"><div class="cs-divider cs-div-gradient"></div></div><div class="cs-div-spacer"></div></div><style>.cs-dividers{padding:20px;font-family:Helvetica,sans-serif;}.cs-div-item{margin-bottom:24px;}.cs-divider{display:flex;align-items:center;width:100%;}.cs-div-line{height:1px;background:#e0e0e0;}.cs-div-dots{justify-content:center;gap:8px;}.cs-div-dots span{width:6px;height:6px;background:#d0b0d0;border-radius:50%;display:block;}.cs-div-text::before,.cs-div-text::after{content:" ";flex:1;height:1px;background:#e0e0e0;}.cs-div-text span{padding:0 16px;font-size:.8em;color:#bbb;text-transform:uppercase;letter-spacing:2px;font-weight:600;white-space:nowrap;}.cs-div-gradient{height:1px;background:linear-gradient(90deg,transparent,#a0449e,transparent);}.cs-div-spacer{height:60px;}</style>'
  });
});
